### ISSUE TITLE
Which Raspberry Pi models are supported?

### ISSUE THREAD

**Issue by smuehlst** [farjump/raspberry-pi#1]
Specifically interesting for me: Is the Raspberry Pi Zero supported?

**Comment by Julio-Guerra** [comment]
Every Raspberry Pi model is supported.
Stated in the README.

**Comment by smuehlst** [comment]
I see, my fault, sorry... I scanned the table of contents for system requirements, and I missed the preceding  sentence about the support for all Raspberry Pi Models. I'm looking forward to try out Alpha with Circle.
Thanks.
